# Generated by Django 4.2.4 on 2023-08-29 14:19

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    model = apps.get_model("users", "User")
    for row in model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
