# Generated by Django 4.2.4 on 2023-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230829_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(default=12345678901, max_length=18, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default=63984512451, max_length=16, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
