# Generated by Django 4.2.4 on 2023-09-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cpf_cnpj_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
