# Generated by Django 4.2.4 on 2023-08-25 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=45, null=True)),
                ('aplicacao', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pagamento_cartao', models.BooleanField(default=False)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provedor')),
                ('nome_arquivo', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.cidade')),
            ],
            options={
                'verbose_name': 'Provedor',
                'verbose_name_plural': 'Provedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('cpf_cnpj_indicador', models.CharField(blank=True, max_length=18, null=True)),
                ('nome_indicador', models.CharField(blank=True, max_length=200, null=True)),
                ('fechou_contrato', models.BooleanField(default=False)),
                ('bonuspago', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.cidade')),
                ('provedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provedor.provedor')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['nome'],
            },
        ),
    ]
