# Generated by Django 4.2.4 on 2023-08-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cidade_estado'),
        ('provedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='bonuspago',
            new_name='bonus_pago',
        ),
        migrations.RemoveField(
            model_name='provedor',
            name='nome_arquivo',
        ),
        migrations.AlterField(
            model_name='lead',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='provedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='provedor.provedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='aplicacao',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='logo',
            field=models.ImageField(default=1, upload_to='provedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='telefone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='token',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provedor',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
