# Generated by Django 4.2.4 on 2023-08-29 14:27

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    _models = ["Lead", "Provedor"]
    for _model in _models:
        model = apps.get_model("provedor", _model)
        for row in model.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("provedor", "0003_lead_uuid_provedor_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
