# Generated by Django 4.2.4 on 2023-08-29 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_populate_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cidade",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="uuid"),
        ),
        migrations.AlterField(
            model_name="estado",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="uuid"),
        ),
    ]
